import './global.css'

export const metadata = {
  title: 'Welcome to next-app',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen overflow-y-auto bg-neutral-800">
          <div className="container">
            <main className="flex flex-col">{children}</main>
          </div>
        </div>
      </body>
    </html>
  )
}
